### PR TITLE
feat: add ko-build tests

### PR DESCRIPTION
**Pull request by BobyMCbobs**
test ko build functions

### CODE REVIEW

**Review by ozym — APPROVED** [review]
makes sense, noted about retries.

**Comment by BobyMCbobs** [comment]
currently updating the tests given some small new features like configPath and adding a test for the expected base images

**Comment by BobyMCbobs** [comment]
@ozym, thank you for your earlier review. Needed to make some changes and now got the tests to pass.

added a test for config and base images, and a fixed some behaviours

**Review by ozym — APPROVED** [review]
nice to see tests

**Comment by BobyMCbobs** [comment]
@ozym, thank you!

**Pull request merged**
